### ISSUE TITLE
Record and display whether the `reporting-org/@ref` matches the `organisation-identifier/text()`

### ISSUE THREAD

**Issue by andylolz** [andylolz/org-id-finder#4]
The approach here differs from the one described by @stevieflow in [his IATI discuss post](https://discuss.iatistandard.org/t/getting-to-a-list-of-organisation-references-for-iati-publishers/1060) in the sense that we record information for *all* organisations we find – not just the ones where the `reporting-org/@ref` and `organisation-identifier/text()` match.

However, I think I prefer Steven’s approach, because [publishers are responsible for their own data](http://www.publishwhatyoufund.org/if-you-cant-report-a-pothole/). So we can take as ground truth that a self-reported organisation identifier is correct. And if it’s not correct, it’s clearly for the publisher to fix, so we could pass that work on to them (thereby making this approach more streamlined, more sustainable, while also helping to improve IATI data). For identifiers reported on behalf of another organisation, I suppose it’s a bit less clear who’s responsible.

This ticket represents a halfway house… We record and display that an organisation identifier is self-reported, but we continue to store and display all organisation identifiers we find in org files.

**Comment by andylolz** [comment]
Good demonstration of the importance of this check:

[The org file for TradeMark East Africa](https://aidstream.org/files/xml/tmea-org.xml) currently reports an organisation named “DFID” with org ID `GB-1`. This is DFID’s old org ID – they refer to themselves as `GB-GOV-1`.

**Comment by andylolz** [comment]
Fixed in a777f17f24b4f9649e9f480f8c49fbb677f33062.

**Comment by andylolz** [comment]
Okay, I’ve modified this so that if the org ID and `reporting-org/@ref` *don’t* match, it’s still stored, but with `self_reported=False` set.

**Comment by andylolz** [comment]
I got in touch with [support@iatistandard.org]() [about this](https://github.com/andylolz/org-id-finder/issues/4#issuecomment-364445466). They told me to contact the publisher directly.

**Comment by notshi** [comment]
http://org-id-finder.codeforiati.org/#UG-NGB-5914-1107

![Screenshot-20190723142512-1041x251](https://user-images.githubusercontent.com/1515961/61716055-3e911900-ad56-11e9-8707-1796858e2569.png)
[The org file for Stromme Foundation](https://aidstream.org/files/xml/stromme_ug-org.xml) currently reports as both "DFID" and as themselves with org ID ```UG-NGB-5914-110```. Their current org ID is ```XI-IATI-5914-1107```.

**Comment by andylolz** [comment]
Hi @notshi, thanks for this.

This was discussed on twitter last year:
https://twitter.com/andylolz/status/1049937645370007552

…and before that, on IATI discuss:
https://discuss.iatistandard.org/t/getting-to-a-list-of-organisation-references-for-iati-publishers/1060/15

I don’t think there’s anything I can do about it.

**Comment by andylolz** [comment]
> Their current org ID is `XI-IATI-5914-1107`.

…[on the registry](https://iatiregistry.org/publisher/stromme_ug), you mean. Important to clarify this, because org IDs on the registry are by no means canonical.

**Comment by notshi** [comment]
Ahh! Wasn't aware of the twitter discussion - I followed your template "The org file for xxx currently reports as xxx with org ID xxx." and thought it'd be good to raise here for posterity by adding to the closed issue.

**Comment by andylolz** [comment]
Aha, I see! Absolutely – no harm in adding it here for posterity.

I haven’t checked in on it for a while – perhaps I should send another message to try and get the issue resolved.

**Comment by notshi** [comment]
Would be good to have a template to send to publishers for issues like this. Might be helpful for citizens/journalists when they encounter data issues.

**Comment by notshi** [comment]
ps: I've sent an email to the contact (May Kamoga) - hopefully, something comes up.

**Comment by andylolz** [comment]
Sounds good. I’d also suggest looping in the support@ email address, just because it’s probably useful for there to be some centralised log of publication issues.

**Comment by andylolz** [comment]
> [The org file for Stromme Foundation](https://aidstream.org/files/xml/stromme_ug-org.xml) currently reports as both "DFID" and as themselves with org ID `UG-NGB-5914-110`. Their current org ID is `XI-IATI-5914-1107`.

Since this is a data issue, it would be cool to raise it on https://github.com/codeforIATI/iati-data-bugtracker . (At some point soon, I’ll add some more explanation to that repo to make it a bit clearer what the vision is!)
